import { defineRoutes } from '@/routes/definitions'

const loadNetworkAccessPage = () => import('./page')

export const networkAccessRoutes = defineRoutes([
  {
    meta: {
      id: 'network-access',
      path: '/network-access',
      title: '网络访问',
      description: '内网网络访问工作台',
      icon: 'IconShield',
      group: 'identity',
      workbenchId: 'security',
      requiresAuth: true,
      tabbar: false,
      navVisible: false,
      permissionKeysAny: [
        'network_access.endpoint_devices.view',
        'network_access.sites.view',
        'network_access.spaces.view',
        'network_access.resources.view',
        'network_access.gateways.view',
        'network_access.mihomo_profiles.view',
        'network_access.telemetry.view',
        'network_access.enrollments.view',
        'network_access.access_grants.view',
        'network_access.policy.view',
      ],
      scopeMode: 'passive',
      workspace: 'system',
    },
    shell: 'app',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-devices',
      path: '/network-access/devices',
      title: '设备',
      navVisible: true,
      menuId: 'network-access-devices',
      permissionKey: 'network_access.endpoint_devices.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-sites',
      path: '/network-access/sites',
      title: '站点',
      navVisible: true,
      menuId: 'network-access-sites',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-user-admission',
      path: '/network-access/user-admission',
      title: '用户入网',
      navVisible: true,
      menuId: 'network-access-user-admission',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-settings',
      path: '/network-access/settings',
      title: '入网设置',
      navVisible: true,
      menuId: 'network-access-settings',
      permissionKeysAny: ['network_access.sites.view', 'network_access.enrollments.view'],
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-wifi',
      path: '/network-access/wifi',
      title: 'Wi-Fi 入网',
      navVisible: false,
      menuId: 'network-access-wifi',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    redirectTo: '/network-access/user-admission',
  },
  {
    meta: {
      id: 'network-access-wired',
      path: '/network-access/wired',
      title: '有线入网',
      navVisible: false,
      menuId: 'network-access-wired',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    redirectTo: '/network-access/user-admission',
  },
  {
    meta: {
      id: 'network-access-ssids',
      path: '/network-access/ssids',
      title: 'SSID',
      navVisible: false,
      menuId: 'network-access-ssids',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    redirectTo: '/network-access/settings',
  },
  {
    meta: {
      id: 'network-access-nas-bindings',
      path: '/network-access/nas-bindings',
      title: '网络设备',
      navVisible: false,
      menuId: 'network-access-nas-bindings',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    redirectTo: '/network-access/settings',
  },
  {
    meta: {
      id: 'network-access-radius-services',
      path: '/network-access/radius-services',
      title: 'RADIUS 服务',
      navVisible: false,
      menuId: 'network-access-radius-services',
      permissionKey: 'network_access.enrollments.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    redirectTo: '/network-access/settings',
  },
  {
    meta: {
      id: 'network-access-site-profile-bindings',
      path: '/network-access/site-profile-bindings',
      title: '接入等级',
      navVisible: true,
      menuId: 'network-access-site-profile-bindings',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-sessions',
      path: '/network-access/sessions',
      title: '会话',
      navVisible: true,
      menuId: 'network-access-sessions',
      permissionKey: 'network_access.sites.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-telemetry',
      path: '/network-access/telemetry',
      title: '遥测',
      navVisible: true,
      menuId: 'network-access-telemetry',
      permissionKey: 'network_access.telemetry.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-spaces',
      path: '/network-access/spaces',
      title: '网络空间',
      navVisible: true,
      menuId: 'network-access-spaces',
      permissionKey: 'network_access.spaces.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-resources',
      path: '/network-access/resources',
      title: '资源',
      navVisible: true,
      menuId: 'network-access-resources',
      permissionKey: 'network_access.resources.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-gateways',
      path: '/network-access/gateways',
      title: '网关',
      navVisible: true,
      menuId: 'network-access-gateways',
      permissionKey: 'network_access.gateways.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-enrollments',
      path: '/network-access/enrollments',
      title: '运行时注册',
      navVisible: true,
      menuId: 'network-access-enrollments',
      permissionKey: 'network_access.enrollments.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-access-grants',
      path: '/network-access/access-grants',
      title: '访问授权',
      navVisible: true,
      menuId: 'network-access-access-grants',
      permissionKey: 'network_access.access_grants.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-policy',
      path: '/network-access/policy',
      title: '策略',
      navVisible: true,
      menuId: 'network-access-policy',
      permissionKey: 'network_access.policy.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-mihomo-profiles',
      path: '/network-access/mihomo-profiles',
      title: '代理隧道',
      navVisible: true,
      menuId: 'network-access-mihomo-profiles',
      permissionKey: 'network_access.mihomo_profiles.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-proxy-overview',
      path: '/network-access/proxy-overview',
      title: '流量概览',
      navVisible: true,
      menuId: 'network-access-proxy-overview',
      permissionKey: 'network_access.telemetry.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
  {
    meta: {
      id: 'network-access-proxy-connections',
      path: '/network-access/proxy-connections',
      title: '用户连接',
      navVisible: true,
      menuId: 'network-access-proxy-connections',
      permissionKey: 'network_access.telemetry.view',
    },
    shell: 'app',
    inheritMetaFrom: 'network-access',
    load: loadNetworkAccessPage,
  },
] as const)
