import type { ReactNode } from 'react'
import {
  AlertOutlined,
  AppstoreOutlined,
  BellOutlined,
  CodeOutlined,
  CommentOutlined,
  ControlOutlined,
  DashboardOutlined,
  DeploymentUnitOutlined,
  ApartmentOutlined,
  DesktopOutlined,
  DockerOutlined,
  FileOutlined,
  GlobalOutlined,
  HddOutlined,
  HistoryOutlined,
  InfoCircleOutlined,
  MenuOutlined,
  OrderedListOutlined,
  PictureOutlined,
  SafetyOutlined,
  SendOutlined,
  SettingOutlined,
  SyncOutlined,
  TeamOutlined,
  UserOutlined,
} from '@ant-design/icons'

const ICONS: Record<string, ReactNode> = {
  gauge: <DashboardOutlined />,
  server: <HddOutlined />,
  desktop: <DesktopOutlined />,
  cluster: <ApartmentOutlined />,
  puzzle: <DeploymentUnitOutlined />,
  shield: <SafetyOutlined />,
  boxes: <AppstoreOutlined />,
  cog: <SettingOutlined />,
  network: <SendOutlined />,
  waves: <HddOutlined />,
  globe: <GlobalOutlined />,
  bell: <BellOutlined />,
  users: <TeamOutlined />,
  bot: <CommentOutlined />,
  image: <PictureOutlined />,
  blocks: <AppstoreOutlined />,
  flavor: <ControlOutlined />,
  code: <CodeOutlined />,
  activity: <SendOutlined />,
  history: <HistoryOutlined />,
  info: <InfoCircleOutlined />,
  sync: <SyncOutlined />,
  'panels-top-left': <SettingOutlined />,
  megaphone: <BellOutlined />,
  'menu-square': <MenuOutlined />,
  'clipboard-list': <OrderedListOutlined />,
  'file-clock': <FileOutlined />,
  siren: <AlertOutlined />,
  user: <UserOutlined />,
  docker: <DockerOutlined />,
}

export const MENU_ICON_OPTIONS = [
  { value: 'gauge', label: 'Dashboard' },
  { value: 'server', label: 'Server' },
  { value: 'desktop', label: 'Desktop' },
  { value: 'cluster', label: 'Cluster' },
  { value: 'puzzle', label: 'Puzzle' },
  { value: 'shield', label: 'Shield' },
  { value: 'boxes', label: 'Boxes' },
  { value: 'cog', label: 'Cog' },
  { value: 'network', label: 'Network' },
  { value: 'waves', label: 'Storage' },
  { value: 'globe', label: 'Globe' },
  { value: 'bell', label: 'Bell' },
  { value: 'users', label: 'Users' },
  { value: 'bot', label: 'Bot' },
  { value: 'image', label: 'Image' },
  { value: 'blocks', label: 'Blocks' },
  { value: 'flavor', label: 'Flavor' },
  { value: 'code', label: 'Code' },
  { value: 'activity', label: 'Activity' },
  { value: 'history', label: 'History' },
  { value: 'info', label: 'Info' },
  { value: 'sync', label: 'Sync' },
  { value: 'panels-top-left', label: 'Panels' },
  { value: 'megaphone', label: 'Megaphone' },
  { value: 'menu-square', label: 'Menu' },
  { value: 'clipboard-list', label: 'Clipboard' },
  { value: 'file-clock', label: 'File Clock' },
  { value: 'siren', label: 'Alert' },
  { value: 'user', label: 'User' },
  { value: 'docker', label: 'Docker' },
].map((item) => ({ ...item, preview: ICONS[item.value] ?? <MenuOutlined /> }))

export function resolveMenuIcon(iconKey?: string) {
  return ICONS[String(iconKey || '').trim()] ?? <MenuOutlined />
}

export function isKnownMenuIcon(iconKey?: string) {
  return Object.prototype.hasOwnProperty.call(ICONS, String(iconKey || '').trim())
}
